Repository aceleradora-TW/acelera-mais-api, pull requests merged in 2022-01, with the labels that each got.

#113 refactor: Padronização do prefixo das funções do hiringProcess
  src/controllers/exercise/index.ts
  src/controllers/hiring-process/index.ts
  src/routes.ts
Labels: BACK-END, refatorar

#114 refact: padronização dos prefixos das funções - controllers/exercise
  src/controllers/exercise/index.ts
  src/routes.ts
Labels: BACK-END

#124 117/transformar em função controller/http response handler
  src/controllers/HttpResponseHandler.ts
  src/controllers/auth/index.ts
  src/controllers/candidate/index.ts
  src/controllers/evaluation/index.ts
  src/controllers/exercise/index.ts
  src/controllers/hiring-process/index.ts
  test/controllers/HttpResponseHandler.test.ts
Labels: Nv: Médio, refatorar

#125 refactor(service/evaluationRequest): remove classes e transforma em f…
  src/controllers/evaluation/index.ts
  src/service/evaluation/EvaluationRequest.ts
Labels: Nv: Médio, melhorias, BACK-END, refatorar

#126 121/refact: remover classe e transformar em função Service/ExerciseService
  src/controllers/exercise/index.ts
  src/service/exercise/ExerciseService.ts
Labels: Nv: Médio, melhorias, BACK-END, refatorar

#128 refactor(hiring-process/HiringProcessService): remove classe e tranforma em funçao
  src/controllers/hiring-process/index.ts
  src/service/hiring-process/HiringProcessService.ts
  test/service/hiring-process/HiringProcessServices.test.ts
Labels: Nv: Médio, melhorias, BACK-END, refatorar

#129 122/refact remover classe e transformar em funcao service hiring process request
  src/controllers/exercise/index.ts
  src/controllers/hiring-process/index.ts
  src/service/hiring-process/HiringProcessRequest.ts
Labels: Nv: Médio, melhorias, BACK-END, refatorar
